'use strict';
const {test}=require('node:test'),a=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),crypto=require('node:crypto'),{spawn}=require('node:child_process');
const db=require('/app/packages/api/src/db'),hooks=require('/app/packages/api/src/webhooks'),ep=require('/app/packages/api/src/webhook-endpoints');
const {Pool}=require('/app/node_modules/pg');const admin=new Pool({connectionString:'postgres://postgres:isolated-fixture-only@127.0.0.1:5432/mailmint_delta_0909'});
const proof={mode:'Exact running image, isolated real PostgreSQL and HTTP, separate worker processes; NO production outage',received:[],cases:[],workers:[]};let server,account,box,endpoint,hold=false;const workers=new Set(),held=[];
const delay=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn,ms=12000){const end=Date.now()+ms;while(Date.now()<end){const v=await fn();if(v)return v;await delay(30);}throw Error('poll deadline');}
async function row(id){return (await admin.query('SELECT * FROM webhook_deliveries WHERE id=$1',[id])).rows[0];}
async function start(){const c=spawn(process.execPath,['-e',"require('/app/packages/api/src/webhooks').startWorker();setInterval(()=>{},1000);console.log('READY')"],{env:process.env,stdio:['ignore','pipe','pipe']});workers.add(c);const record={pid:c.pid,stderr:''};proof.workers.push(record);c.stderr.on('data',d=>{record.stderr+=String(d)});c.stdout.on('data',d=>{record.stderr+=String(d)});return new Promise((resolve,reject)=>{c.stdout.on('data',d=>{if(String(d).includes('READY'))resolve(c)});c.once('error',reject);});}
async function stop(c){if(!c||c.exitCode!==null||c.signalCode!==null)return;const p=new Promise(r=>c.once('exit',r));c.kill('SIGTERM');await p;workers.delete(c);}
async function stopAll(){for(const c of [...workers])await stop(c);for(const r of held.splice(0))if(!r.destroyed)r.end('released');}
async function queue(){return hooks.enqueue({messageId:'msg_owned_delta0909',accountId:account,url:endpoint.url,endpointId:endpoint.id});}
async function setup(){await require('/app/packages/api/src/migrate').migrate();account=(await db.query("INSERT INTO accounts(email,password_hash) VALUES('owned-delta0909@example.invalid','not-login') RETURNING id")).rows[0].id;box=(await db.query("INSERT INTO mailboxes(id,account_id,token,name) VALUES('mb_owned_delta0909',$1,'owneddelta0909','Own QA') RETURNING *",[account])).rows[0];await db.query("INSERT INTO messages(id,mailbox_id,account_id,status,result) VALUES('msg_owned_delta0909',$1,$2,'parsed',$3)",[box.id,account,{fields:{total:{value:31.5,confidence:1}}}]);server=http.createServer((req,res)=>{let body='';req.on('data',b=>body+=b);req.on('end',()=>{const sig=Object.fromEntries(req.headers['x-mailmint-signature'].split(',').map(x=>x.split('=')));proof.received.push({time:new Date().toISOString(),id:req.headers['x-mailmint-delivery'],signatureValid:crypto.createHmac('sha256',endpoint.secret).update(sig.t+'.'+body).digest('hex')===sig.v1,hold});if(hold){held.push(res);return;}res.end('ok');});});await new Promise(r=>server.listen(0,'127.0.0.1',r));endpoint=await ep.create(box,{url:'http://127.0.0.1:'+server.address().port+'/owned'});}
test('MailMint remaining real-isolated acceptance',async t=>{try{a.ok(process.env.DATABASE_URL.endsWith('/mailmint_delta_0909'));a.equal(process.env.MAILMINT_BILLING,'0');await setup();
await t.test('two healthy workers must not concurrently deliver the same in-flight row',async()=>{hold=true;const id=await queue();let before;try{const w1=await start();await until(()=>proof.received.some(x=>x.id===id));const w2=await start();await delay(900);before=await row(id);const requests=proof.received.filter(x=>x.id===id);proof.cases.push({name:'healthy multiworker exclusion',id,requests,before,workers:[w1.pid,w2.pid]});a.equal(requests.length,1,'Two healthy workers simultaneously sent one held delivery');}finally{hold=false;for(const r of held.splice(0))r.end('ok');await until(async()=>(await row(id)).delivered_at);await stopAll();}});
await t.test('actual DB login outage emits errors, queued work resumes after restoration',async()=>{const id=await queue();await admin.query('ALTER ROLE qa NOLOGIN');await admin.query("SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE usename='qa'");let c;try{c=await start();await delay(1500);a.equal(proof.received.filter(x=>x.id===id).length,0);const state=await row(id);a.equal(state.attempt,0);proof.cases.push({name:'real database access outage',id,during:state});}finally{await admin.query('ALTER ROLE qa LOGIN');}await until(async()=>(await row(id)).delivered_at,15000);await stop(c);const wr=proof.workers.find(w=>w.pid===c.pid);a.match(wr.stderr,/not permitted to log in|28000|login/i);a.equal(proof.received.filter(x=>x.id===id).length,1);proof.cases.push({name:'database restored',id,final:await row(id),workerErrors:wr.stderr});});
await t.test('unsubscribe queued endpoint cascades only its deliveries; sibling survives; recreate gets new identity',async()=>{const first=endpoint;const sibling=await ep.create(box,{url:first.url+'/sibling'});const ids=await hooks.enqueueForMailbox({messageId:'msg_owned_delta0909',accountId:account,mailboxId:box.id});a.equal(ids.length,2);await ep.remove(account,first.id);a.equal((await ep.listFor(box.id)).length,1);a.equal((await admin.query('SELECT count(*)::int n FROM webhook_deliveries WHERE endpoint_id=$1',[first.id])).rows[0].n,0);const left=(await admin.query('SELECT * FROM webhook_deliveries WHERE endpoint_id=$1',[sibling.id])).rows;a.equal(left.length,1);const fresh=await ep.create(box,{url:first.url});a.notEqual(fresh.id,first.id);a.notEqual(fresh.secret,first.secret);proof.cases.push({name:'unsubscribe queued and recreate',deleted:first.id,sibling:sibling.id,replacement:fresh.id,siblingQueue:left.map(x=>x.id)});await ep.remove(account,sibling.id);endpoint=fresh;});
await t.test('all actual receipts retain expected endpoint HMAC',async()=>{a.ok(proof.received.every(x=>x.signatureValid));});
}finally{await admin.query('ALTER ROLE qa LOGIN').catch(()=>{});await stopAll();if(account)await admin.query('DELETE FROM accounts WHERE id=$1 AND email=$2',[account,'owned-delta0909@example.invalid']);proof.cleanup={};for(const table of ['accounts','mailboxes','messages','webhook_endpoints','webhook_deliveries','mailbox_schema_versions']){proof.cleanup[table]=(await admin.query('SELECT count(*)::int n FROM '+table)).rows[0].n;a.equal(proof.cleanup[table],0);}if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}await db.pool.end();await admin.end();proof.finished=new Date().toISOString();fs.writeFileSync('/proof/deep-result.json',JSON.stringify(proof,null,2));}});
